package mapa.pds2.bancowzt;

/**
 *
 * @author User
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    Cliente cliente = new Cliente();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ScoreTela = new javax.swing.JTextField();
        BotaoOkScoreTela = new javax.swing.JButton();
        RendaTela = new javax.swing.JTextField();
        BotaoOkRendaTela = new javax.swing.JButton();
        IdadeTela = new javax.swing.JTextField();
        BotaoOkIdadeTela = new javax.swing.JButton();
        BotaoCalcula = new javax.swing.JButton();
        ValorDisponivelTela = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco WZT");

        ScoreTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ScoreTela.setText("Score  (0 a 1000)");
        ScoreTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreTelaActionPerformed(evt);
            }
        });

        BotaoOkScoreTela.setText("Ok");
        BotaoOkScoreTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkScoreTelaActionPerformed(evt);
            }
        });

        RendaTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RendaTela.setText("Renda");
        RendaTela.setToolTipText("");

        BotaoOkRendaTela.setText("Ok");
        BotaoOkRendaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkRendaTelaActionPerformed(evt);
            }
        });

        IdadeTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IdadeTela.setText("Idade");
        IdadeTela.setToolTipText("");

        BotaoOkIdadeTela.setText("Ok");
        BotaoOkIdadeTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkIdadeTelaActionPerformed(evt);
            }
        });

        BotaoCalcula.setText("Calcula");
        BotaoCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalculaActionPerformed(evt);
            }
        });

        ValorDisponivelTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ValorDisponivelTela.setText("Valor Disponivel");
        ValorDisponivelTela.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdadeTela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoOkIdadeTela)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScoreTela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoOkScoreTela))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RendaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoOkRendaTela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotaoCalcula)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ValorDisponivelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScoreTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoOkScoreTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCalcula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RendaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoOkRendaTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorDisponivelTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdadeTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoOkIdadeTela, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScoreTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreTelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScoreTelaActionPerformed

    private void BotaoOkScoreTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkScoreTelaActionPerformed
        if (Integer.parseInt(ScoreTela.getText()) < 0 || Integer.parseInt(ScoreTela.getText()) > 1000) {
            ScoreTela.setText("Score  (0 a 1000)");
        } else {
            Cliente.setScore(Integer.parseInt(ScoreTela.getText()));
        }
    }//GEN-LAST:event_BotaoOkScoreTelaActionPerformed

    private void BotaoOkRendaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkRendaTelaActionPerformed
        if (Integer.parseInt(RendaTela.getText()) < 0) {
            RendaTela.setText("Renda");
        } else {
            Cliente.setRenda(Integer.parseInt(RendaTela.getText()));
        }
    }//GEN-LAST:event_BotaoOkRendaTelaActionPerformed

    private void BotaoOkIdadeTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkIdadeTelaActionPerformed
        if (Integer.parseInt(IdadeTela.getText()) < 0 || Integer.parseInt(IdadeTela.getText()) > 130) {
            IdadeTela.setText("Idade");
        } else {
            Cliente.setIdade(Integer.parseInt(IdadeTela.getText()));
        }        
    }//GEN-LAST:event_BotaoOkIdadeTelaActionPerformed

    private void BotaoCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalculaActionPerformed
        CalculadoraEmprestimo.CalculaEmprestimo();
        ValorDisponivelTela.setText(String.valueOf(CalculadoraEmprestimo.getValorEmprestimo()));
    }//GEN-LAST:event_BotaoCalculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCalcula;
    private javax.swing.JButton BotaoOkIdadeTela;
    private javax.swing.JButton BotaoOkRendaTela;
    private javax.swing.JButton BotaoOkScoreTela;
    private javax.swing.JTextField IdadeTela;
    private javax.swing.JTextField RendaTela;
    private javax.swing.JTextField ScoreTela;
    private javax.swing.JTextField ValorDisponivelTela;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
